### PR TITLE
Configurable hrefs for listings (enables use of s3 website redirect keys)

### PR DESCRIPTION
**Pull request by yofreke**
Original: https://github.com/rgrp/s3-bucket-listing/pull/48

Only thing I did was update the readme so that this PR can get merged.

### CODE REVIEW

**Comment by client9** [comment]
Thanks all for getting this stared.

This is also needed if you use the CloudFront CDN in front of an S3 origin.  The nav works great but all the links point to the origin, not the custom domain (using CloudFront).

Unfortunately the PR here has some problems

Original PR (with added comments)

``` js
if (typeof BUCKET_URL == 'undefined') {
  var BUCKET_URL = location.protocol + '//' + location.hostname;
} else if (BUCKET_WEBSITE_URL == 'undefined') {  // OOPS: missing typeof
  var BUCKET_WEBSITE_URL = BUCKET_URL;  
}

// OOPS BUCKET_WEBSITE_URL can be undefined!!

if (typeof BUCKET_NAME != 'undefined') {
    // if bucket_url does not start with bucket_name,
    // assume path-style url
    if (!~BUCKET_URL.indexOf(location.protocol + '//' + BUCKET_NAME)) {
        BUCKET_URL += '/' + BUCKET_NAME;
    }
}
```

New Patch:

``` js
if (typeof BUCKET_URL == 'undefined') {
  var BUCKET_URL = location.protocol + '//' + location.hostname;
}

if (typeof BUCKET_NAME != 'undefined') {
    // if bucket_url does not start with bucket_name,
    // assume path-style url
    if (!~BUCKET_URL.indexOf(location.protocol + '//' + BUCKET_NAME)) {
        BUCKET_URL += '/' + BUCKET_NAME;
    }
}

if (typeof BUCKET_WEBSITE_URL == 'undefined') {
  var BUCKET_WEBSITE_URL = BUCKET_URL;
}
```

Finally not sure about the name `BUCKET_WEBSITE_URL`.  I'm not exactly sure of the original author's intentions.. maybe download_url or target_url might be better.   In the CloudFront case it's not a bucket at all.  That said, I can live with it.

not sure if @yofreke wants to update the PR.  I"m happy to make a new one if that is easier.

Thanks all

n

**Comment by client9** [comment]
(side note, once merged in I can make a PR to update the README for use with CloudFront)
(thanks again)

**Comment by client9** [comment]
another problem with this PR is that the NAV also needs updating

Original:

``` js
function buildNavigation(info) {
  var root = '<a href="?prefix=">' + BUCKET_URL + '</a> / '
```

Should be:

``` js
function buildNavigation(info) {
  var root = '<a href="?prefix=">' + BUCKET_WEBSITE_URL + '</a> / '
```

OR

``` js
function buildNavigation(info) {
  var home = BUCKET_WEBSITE_URL === "" ? location.hostname : BUCKET_WEBSITE_URL;
  var root = '<a href="?prefix=">' + home + '</a> / ';
```

I think the last one is "always right" but I'm not as familiar with the use cases here.

**Comment by yofreke** [comment]
Good catches, thanks.  "BUCKET_WEBSITE_URL" seems okay to me, not too picky.  Maybe could change it to "PUBLIC_URL".  "download" and "target" are a bit vague in my use case (hosting a couple static docs sites).

Went with `BUCKET_WEBSITE_URL` on the second issue since the configuration is there (good for testing locally, browsing random buckets unrelated to current location, public vs private frontends).  Might be nice to use `location.hostname` by default though, instead of `BUCKET_URL`.

**Comment by client9** [comment]
LGTM

thanks @yofreke  I think this is good enough to get merged in for round 1

We can make other changes once accepted and merged in by @rgrp

**Comment by rufuspollock** [comment]
Thanks @yofreke and @client9 for the great work tidying up here and reviewing. It is now clear to me what this feature is 😄  and that it should have no side-effects.

I'll merge now and it would be great if you can confirm you are happy to license your contributions under the MIT license.

**Comment by client9** [comment]
yes, confirm, I donate all code, and MIT 👍

**Comment by yofreke** [comment]
Of course, ty

**Pull request merged**
