### PR TITLE
Suggested approach for #3, to only show the current directory

### PR DESCRIPTION
**Pull request by alza-bitz**
Hi there,

Please take a look at these changes, I've tried with various s3 buckets and it seems to be working well.

Thanks

### CODE REVIEW

**Comment by rufuspollock** [comment]
@alzadude this looks great and would like to merge but i don't want the eclipse settings etc (https://github.com/nineworthies/s3-bucket-listing/commit/f4568dc0724dc48b2df0ac9ee04d2810f1ecadcf). Any way you can resubmit with just the patch to the code :-)

**Comment by rufuspollock** [comment]
@alzadude this works perfectly. I'm closing this request now as I've merged your patch directly (by grabbing the changes in your 2nd change and applying).

**Comment by alza-bitz** [comment]
Hi there,

I've been a bit busy of late and didn't quite get round to removing the Eclipse settings!

Thanks, Alex.

**Comment by rufuspollock** [comment]
@alzadude no problem and the patch is in :-)

**Pull request closed without merging**
