### PR TITLE
Exclude multipe files

### PR DESCRIPTION
**Pull request by PcoWegenenVerkeer**

### CODE REVIEW

**Comment by rufuspollock** [comment]
@PcoWegenenVerkeer what's the difference between this PR and #70 ?

**Comment by p3d** [comment]
@rufuspollock I believe one PR has the code change and the other changes the example code in the index.html file.

**Comment by rufuspollock** [comment]
@p3d hmmm - it would be good to get these as one PR ...

**Comment by rufuspollock** [comment]
Out of date

**Pull request closed without merging**
