### PR TITLE
Support both path and virtualhost S3 buckets

### PR DESCRIPTION
**Pull request by lorengordon**
I made a simple change to support both path-style and virtualhost-style urls for S3 buckets, using a new parameter, `BUCKET_NAME`. I did lump in some minor styling changes (wasn't actually planning to open a pull-request, but figured I might as well). I can reorganize the commits if you want to separate things out so it's easier to review.

### CODE REVIEW

**Comment by lorengordon** [comment]
If you want to test how it looks/works, feel free to point an 'index.html' at `https://lorengordon.github.io/s3-bucket-listing/list.js`

**Comment by rufuspollock** [comment]
@lorengordon thanks for the contribution - really great to get. Breaking this out might be useful as I'm not quite sure I understand the change. For example, could you clarify:
- What is supported now that wasn't before
- Are there breaking changes in this (e.g. does BUCKET_NAME interact with BUCKET_URL in any way and if so how)

**Comment by lorengordon** [comment]
@rgrp, the meat of the change is the `if` block in lines [9-15](https://github.com/rgrp/s3-bucket-listing/pull/40/files#diff-813b4112d08b11dec86f115d77ef9d65R9) of list.js. Everything else is either documentation or minor changes to some visual component of the directory listing.

Without this, I was never able to get both path- and virtualhost-based URLs to work. I can't remember exactly which method did work and which didn't. I _think_ it was virtualhost that worked, but path did not. http://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html

I only serve the index straight out of the S3 endpoint, not a website, so I didn't actually try setting BUCKET_URL and BUCKET_NAME at the same time. I think it would work, based on the logic, but only if BUCKET_URL were the s3 endpoint, and BUCKET_NAME were of course the bucket name.

**Comment by rufuspollock** [comment]
@lorengordon it would be useful to show what is not working right now. Both path and virtualhost stuff _should_ be working (though they may not be!)

I would definitely like to get this contributions in - again would it be worth splitting out any minor doc changes from the more substantive change. We can then get docs stuff in and then review the major change.

**Comment by lorengordon** [comment]
Some work commitments picked up a bit so it might be a week or two before I can split things out, but who knows, I might be able knock it out today. You want a pull request with just one commit containing the substantive change? And a better idea of what exactly didn't work?

**Comment by rufuspollock** [comment]
@lorengordon one PR with the "trivial" fixes e.g. docs etc and one PR with substantive change. Also if you can doc what was not working that (should) have been thats useful.

**Comment by lorengordon** [comment]
Closing this PR in favor of https://github.com/rgrp/s3-bucket-listing/pull/41.

**Pull request closed without merging**
