### PR TITLE
AWS is enforcing the use of SSL

### PR DESCRIPTION
**Pull request by pudo**
So you need to use a different bucket URL.

### CODE REVIEW

**Comment by rufuspollock** [comment]
@pudo are AWS enforcing s3? Could you link to any relevant info ...

**Comment by pudo** [comment]
Check out http://data.openspending.org/ -- 

```
Request URL:http://data.openspending.org.s3-eu-west-1.amazonaws.com/?delimiter=/
Request Method:GET
Status Code:307 Internal Redirect
...
Location:https://s3-eu-west-1.amazonaws.com/data.openspending.org/?delimiter=/
```

**Comment by rufuspollock** [comment]
Where are you seeing this? For me the site works fine and looking at network traffic in browser I'm not seeing a redirect. BTW I'm on irc.

**Comment by pudo** [comment]
Ooooh, horrible suspicion: I use HTTPS Everywhere as a browser plugin. Maybe they're fucking with the AWS API.

**Comment by rufuspollock** [comment]
I was just about to suggest that :-) i.e. do you have some kind of plugin :-) (we could try and detect that in the bucket listing script but that is probably painful).

**Pull request merged**
