### PR TITLE
add pollyfills to allow this to work in Internet Explorer

### PR DESCRIPTION
**Pull request by daxgames**

### CODE REVIEW

**Comment by rufuspollock** [comment]
Thanks - really appreciate the contribution!

Which IE versions does this add support for? And could you add a comment about that in the code?

**Comment by daxgames** [comment]
I only tested it with IE 11.

**Comment by rufuspollock** [comment]
@daxgames and did it not work before doing this PR?

**Comment by daxgames** [comment]
It did not.

**Pull request merged**
