### PR TITLE
Row shading. CSS & Shiny stuff

### PR DESCRIPTION
**Pull request by fuzzball03**
## This consists primarily of implementing shading & other visual enhancments
- This is **part 3 of 3** of multiple pull requests as requested by @rufuspollock in #59 

### Cell Shading

This consisted of changing a few things
1. `S3.css` Has been added
2. Added a few buttons to the listing and attached a couple of listeners to it
3. Rewrote the current `renerRow` w/ __<span>__ implementation, and replaced it with __tables__. This also means I could remove several other pieces of code. It still needs considerable cleanup of existing code.

This has two buttons currently added. 
- `my cell shading`:  My implmentation of the cell shading.
1. More complex, requires more math processing(neglabible)
2. Dirty: Each row is assigned a class of `rowOdd` or `rowEven`
- `ez cell shading`: Uses a simple CSS selector. 
1. Wasting my time... (I wrote my code before discovering this already there waiting for me. Duh!)
2. Easily configurable via css, applied with a single class toggle

## TODO
1. Which implementation to use? I want to say `ez` is the way to go. Thoughts?
2. Suggestions or prefrences or specific coloring?
3. Can we enable it by default?
4. Where to stick button/link to toggle row shading?

### `clang-format` and formatting
I use __clang-format__ for most of my code based on the '_Google API_'.
The following are the settings used:

```---
Language: JavaScript
BasedOnStyle: Google
# Use 100 columns for JS.
ColumnLimit: 100
```

### CODE REVIEW

**Comment by fuzzball03** [comment]
After all changed mades a cross #61 #62 & #63 There appears to be NO performance impact - infact, it appears to load more quickly. I'm sure someone with a much larger bucket available to test on can provided better results.
This was performed with a forced refresh/reload. Typical cached results should be even faster.

image

**Comment by ravimartins** [comment]
@fuzzball03 i'm embedding s3-bucket-listing in one of my sites. How can add your css to style the sheet? Sorry about the dumb question, i don't know almost nothing about css and programming.

**Comment by bpesics** [comment]
+1

**Comment by rufuspollock** [comment]
Someone needs to tidy this up and resubmit a pull request for this to be considered for merging :smile:

**Comment by phyllisstein** [comment]
Hey @rufuspollock! I'd be glad to try my hand at a fresh PR. Aside from merge conflicts, is there anything else crying out to you for cleanup? I see some definite issues with code style and a bunch of superfluous comments, but there's stuff that bugs me in the implementation details too and I want to be careful not to overdo it.

**ETA:** Ignore me, after a more careful I feel like the retro styling of the current `master` doesn't need me ““fixing”” it. ❤️

**Comment by rufuspollock** [comment]
@phyllisstein i am open to other fixes - just keep them separate PRs so easy to review one at a time 😄

**Comment by phyllisstein** [comment]
Hah, noted! But I love it as is, I don't want to be the one putting that Bootstrap stank on it.

**Comment by TShostak** [comment]
Hey. I'm using your script to show directory listing on me website. Is there any way to style it? Right now I get directory listing in a very poor format - just plain text in a "pre" tag (only "a" tags are separate). Can I somehow get this listing with more tags to style it? Sorry if it's a dumb question.

**Pull request closed without merging**
