### PR TITLE
Add sort functionality to file list

### PR DESCRIPTION
**Pull request by fuzzball03**
This is a very basic function right now. Simply sorts file list by order of date modified(newest first).
It could easily be expanded/adapted so a variable set on the index page is what determines the sort order.

It does what I need it to do, so I have no plans to expand it to include the above functions.

Feel free to build upon this as you see fit.

### CODE REVIEW

**Comment by rufuspollock** [comment]
@fuzzball03 thanks for the PR - really appreciated. Doing a review now.

**Comment by rufuspollock** [comment]
OK, I've made a couple of line comments. These are definitely a set of useful improvements. Main items:

I think we have a big "all in one" PR. There are at least 3 separate items here:
- sorting
- tidy up + jquery + more compliant html
- shading of rows

It would be really useful to have these separately so we can discuss and merge per item.

More specific:

- It would be nice for the sorting choice to be an option - both to have last modified and the order of it. I think by default we get alphabetic (?) and it would be nice to retain that as default.
- Some changes seem superfluous and should prob not be there e.g. README
- Shading of rows: i'm not sure we want such a big change in by default (but could review better in own PR)

**Comment by fuzzball03** [comment]
Not a problem. Ill split it up.
Read me changes mostly there to distinguish myself fork from the main - no
need to retain that.

**Comment by rufuspollock** [comment]
@fuzzball03 brilliant 😄

**Comment by fuzzball03** [comment]
Close pull request.
@rufuspollock  requested individual pulls for changes.
 See #61 #62 and #63

**Pull request closed without merging**
